### ISSUE TITLE
Lipwig throws error in parsing explain plans with python 2.7.18

### ISSUE THREAD

**Issue by rbalamohan** [t3rmin4t0r/lipwig#6]
python lipwig.py /tmp/query45.sql.explain.txt > q45.7.2.9.dot

`
Traceback (most recent call last):
  File "lipwig.py", line 38, in <module>
    nextInt = counter().__next__
AttributeError: 'itertools.count' object has no attribute '__next__'
`

Python version: 2.7.18

[query45.sql.explain.txt](https://github.com/t3rmin4t0r/lipwig/files/8260233/query45.sql.explain.txt)

This works with `git checkout b11e17e10663819682fc5a21875d2039537d6173`

**Comment by t3rmin4t0r** [comment]
Fixed in 

https://github.com/t3rmin4t0r/lipwig/commit/6178bb8a395e962d60da106559f8e05eff364615
